version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/coinbase/step
    steps:
      - checkout
      - run: export GO111MODULE=on
      - run: go mod download
      - run: go test ./...

